version: '3.8'
services:
  user-service:
    build: ./user-service/
    ports:
      - "8080:8080"

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xmx2g -Xms2g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    #network_mode: "host"
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

  dejavu:
    image: appbaseio/dejavu:3.6.0
    container_name: dejavu
    ports:
      - '1358:1358'
    links:
      - elasticsearch
    networks:
      - elastic


  zookeeper:
    container_name: zookeeper
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    volumes:
      - zookeeper_data:/bitnami
    networks:
      - elastic
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
      container_name: kafka
      image: 'docker.io/bitnami/kafka:2-debian-10'
      ports:
        - '9092:9092'
        - '9093:9093'
      volumes:
        - kafka_data:/bitnami
      networks:
        - elastic
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093
        - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9093
        - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
        - KAFKA_DELETE_TOPIC_ENABLE=true
        - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      depends_on:
        - zookeeper

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - '28180:8080'
    networks:
      - elastic
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092

networks:
  elastic:
    driver: bridge

volumes:      
  esdata:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local