filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/app_logs/service.log  # Adjust to your log file location
    close_inactive: 8760h
    scan_frequency: 10s
    fields:
      app: audit-service
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

processors:
  - decode_json_fields:
      fields: [ "msg" ]
      process_array: false
      max_depth: 1
      target: "parsed_msg"
      overwrite_keys: true
      add_error_key: true



output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]  # Adjust the Elasticsearch address as necessary
  index: "filebeat-7.15.2-*"  # Index name pattern

#logging.level: info
#logging.to_files: true
#logging.files:
#  path: /var/log/filebeat
#  name: filebeat.log
#  keepfiles: 7
#  permissions: 0777
#  rotateeverybytes: 10480000 # = 10kB

setup.template.name: "log-events"
setup.template.pattern: "filebeat-7.15.2-*"
